# Generated by Django 3.2.4 on 2021-11-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('internal', 'internal'), ('external', 'external')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tour_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourname', to='eticket.tour_name'),
        ),
    ]
