# Generated by Django 3.2.4 on 2021-11-08 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_reply',
            name='driver_name',
        ),
        migrations.AddField(
            model_name='tickets',
            name='expected_end_tour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tour_duration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tour_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('internal', 'داخلية'), ('external', 'خارجية')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocate_date', models.DateField(blank=True, null=True)),
                ('driver_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='drivers', to='eticket.drivers')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tick_reply', to='eticket.ticket_reply')),
            ],
        ),
    ]
