# Generated by Django 3.2.4 on 2021-11-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='expected_end_tour',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tour_duration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tour_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('internal', 'داخلية'), ('external', 'خارجية')], max_length=20, null=True),
        ),
    ]
