# Generated by Django 3.2.4 on 2021-11-07 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0002_auto_20211106_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_reply',
            name='driver_name',
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocate_date', models.DateField(blank=True, null=True)),
                ('driver_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='drivers', to='eticket.drivers')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tick_reply', to='eticket.ticket_reply')),
            ],
        ),
    ]
