# Generated by Django 3.2.4 on 2021-11-14 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0002_auto_20211108_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_reply',
            name='car',
        ),
        migrations.AddField(
            model_name='allocation',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='eticket.cars'),
        ),
    ]
