# Generated by Django 3.1.3 on 2021-11-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0002_auto_20211102_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('داخلية', 'internal'), ('external', 'external')], max_length=20, null=True),
        ),
    ]
