# Generated by Django 3.2.4 on 2021-11-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0003_auto_20211114_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
