# Generated by Django 3.1.3 on 2021-11-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0004_auto_20211103_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='tour_type',
            field=models.CharField(blank=True, choices=[('internal', 'داخلية'), ('external', 'خارجية')], max_length=20, null=True),
        ),
    ]
