# Generated by Django 3.2.4 on 2021-11-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0004_allocation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='unallocated_days',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
