# Generated by Django 3.2.4 on 2021-11-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0005_tickets_unallocated_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='allocation_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket_reply',
            name='memorandum_statue',
            field=models.CharField(choices=[('تم الاستلام', 'تم الاستلام'), ('لم يتم استلام المذكرة', 'لم يتم استلام المذكرة'), ('خطأ في المذكرة', 'خطأ في المذكرة')], default=False, max_length=30),
        ),
    ]
