# Generated by Django 3.2.4 on 2021-11-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0005_auto_20211103_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='expected_end_tour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='tour_duration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tour_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Tour_Name',
        ),
    ]
