# Generated by Django 3.2.4 on 2021-11-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0006_auto_20211103_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
